ecommerceapp/urls.py
from django.urls import path
from .views import *

app_name="ecommerceapp"
urlpatterns=[
path("",HomeView.as_view()),



]

ecommerceproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("ecommerceapp.urls"))
]
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)	

ecommerceapp/models.py
from django.db import models
from django.contrib.auth.models import User


class EcommerceAdmin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    mobile = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    mobile = models.CharField(max_length=30, null=True, blank=True)
    email = models.EmailField()
    image = models.ImageField(upload_to="customers")
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.user.username


class ProductCategory(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(null=True, blank=True, unique=True)
    root = models.ForeignKey(
        'self', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    product_id = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to="products")
    description = models.TextField()
    max_retail_Price = models.DecimalField(max_digits=10, decimal_places=2)
    selling_Price = models.DecimalField(max_digits=10, decimal_places=2)
    # stock=models.PositiveIntegerField()

    def __str__(self):
        return self.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return "Cart ID:" + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, null=True, blank=True)
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    rate = models.DecimalField(max_digits=10, decimal_places=2)
    subtotal = models.DecimalField(max_digits=15, decimal_places=2)

    def __str__(self):
        return self.product.title


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    subtotal = models.DecimalField(max_digits=15, decimal_places=2)
    discount = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=15, decimal_places=2)
    order_date = models.DateTimeField(auto_now_add=True)
    city = models.CharField(max_length=200)
    street_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=15)
    delivery_date = models.DateField()

    def __str__(self):
        return self.cart.customer.name + "(Order ID: " + str(self.id) + ")"

ecommerceapp/views.py
from django.shortcuts import render
from django.views.generic import *
from .models import *


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        context['maincategories'] = ProductCategory.objects.filter(
            root=None)
        return context

templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Shop Homepage</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'css/shop-homepage.css' %}">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">My E-Store</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">E-Shop Nepal</h1>
        <div class="list-group">
          {% for category in maincategories %}
          <a href="#" class="list-group-item">{{category.title|title}}</a>
          {% for subcategory in category.productcategory_set.all %}
          
           <li style="padding-left: 30px"><a href="#">{{subcategory.title}}</li></a>

          {% endfor %}
          {% endfor %}
          
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">
      	{% block content %}

      	{% endblock %}

       
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; myeshop.com 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
       
<!-- <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> -->

<div class="row" style="margin-top: 50px;">
{% for product in products %}

<div class="col-lg-4 col-md-6 mb-4">
   <div class="card h-100">
      <a href="#"><img class="card-img-top" src="{{product.image.url}}" style="width: 200px;height: 200px" alt=""></a>
      <div class="card-body">
        <h4 class="card-title">
          <a href="#">{{product.title}}</a>
        </h4>
        <h5>{{product.max_retail_Price}}</h5>
        <p class="card-text">{{product.description|truncatewords:20}}</p>
        <button type="button" class="btn btn-success">Add to Cart</button>


      </div>
      <div class="card-footer">
        <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
      </div>
   </div>
 </div>
 {% endfor %}


</div>
<!-- /.row -->

{% endblock %}